CREATE DATABASE Users
GO

USE Users
GO

CREATE TABLE tbUserInfo(
UserID INT IDENTITY(1,1),
UserName VARCHAR(250) NULL,
Password VARCHAR(100) NULL,
FirstName VARCHAR(100) NULL,
LastName VARCHAR(100) NULL,
BirthDate DATETIME NULL,
Sex VARCHAR(10) NULL,
UserType VARCHAR(20) NULL,
DateCreated DATETIME NOT NULL
)
GO